name: Prebuild

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  unit-test:
    name: Prebuild node addon
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [12, 14, 16]
        architecture: [x86, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
      - run: npm ci
      - run: npm run build
      - run: npm run native_prebuildify
        env:
          CI: true
      - name: Archive prebuild
        uses: papeloto/action-zip@v1
        with:
          files: prebuilds/
          dest: 'win-${{ matrix.architecture }}.zip'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.zip'
